version: "3.9"

services:
  app:
    image: ghcr.io/ranandasatria/fgo24-be-crud:latest

    ports:
      - "8888:8888"
    depends_on:
      - postgres
      - redis
    networks:
      - netapp

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
    volumes:
      - data_postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - netapp

  redis:
    image: redis:7
    restart: always
    volumes:
      - data_redis:/data
    networks:
      - netapp

volumes:
  data_postgres: {}
  data_redis: {}

networks:
  netapp: {}
