services:
  app:
    build: .
    networks:
      - netapp
    ports:
      - 8888:8888
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=1
    volumes:
      - data_postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - netapp

  redis:
    image: redis
    volumes:
      - data_redis:/data
    networks:
      - netapp

volumes:
  data_postgres: {}
  data_redis: {}

networks:
  netapp: {}
