name: Push backend image to GHCR
run-name: Release Image GHCR
on:
  push:
    branches:
      - main
jobs:
  push-image-toghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/ranandasatria/fgo24-be-crud:latest

      - name: Generate .env file from secrets
        run: |
          cat <<EOF > .env
          APP_PORT=${{ secrets.APP_PORT }}
          APP_SECRET=${{ secrets.APP_SECRET }}
          PGHOST=${{ secrets.PGHOST }}
          PGPORT=${{ secrets.PGPORT }}
          PGDATABASE=${{ secrets.PGDATABASE }}
          PGUSER=${{ secrets.PGUSER }}
          PGPASSWORD=${{ secrets.PGPASSWORD }}
          RDADDRESS=${{ secrets.RDADDRESS }}
          RDPASSWORD=${{ secrets.RDPASSWORD }}
          RDDB=${{ secrets.RDDB }}
          EOF

      - name: Copy docker-compose and .env to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: 9301
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          source: "docker-compose.yml,.env"
          target: /home/nanda/deploy


      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: 9301
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            cd /home/nanda/deploy
            docker pull ghcr.io/ranandasatria/fgo24-be-crud:latest
            docker compose down || true
            docker compose up -d
