name: Push backend image to GHCR
run-name: Release Image GHCR
on: [push]
jobs:
  push-image-toghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/ranandasatria/fgo24-be-crud:latest
          build-args: |
            APP_PORT=${{ secrets.APP_PORT }}
            APP_SECRET=${{ secrets.APP_SECRET }}
            PGHOST=${{ secrets.PGHOST }}
            PGPORT=${{ secrets.PGPORT }}
            PGDATABASE=${{ secrets.PGDATABASE }}
            PGUSER=${{ secrets.PGUSER }}
            PGPASSWORD=${{ secrets.PGPASSWORD }}
            RDADDRESS=${{ secrets.RDADDRESS }}
            RDPASSWORD=${{ secrets.RDPASSWORD }}
            RDDB=${{ secrets.RDDB }}
